name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - run: xcodebuild archive -project wkwebview.xcodeproj -scheme wkwebview -archivePath unsigned.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      
      - uses: "finnp/create-file-action@master
            env:
              FILE_NAME: "exportOptions.plist"
              FILE_BASE64: "${{ secrets.EXPORTOPTIONS_PLIST_BASE64 }}"
      - run: |
          xcrun xcodebuild -exportArchive -exportOptionsPlist exportPlist.plist -archivePath unsigned.xcarchive
          ls
 
