name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: actual build
      run: set -o pipefail && xcodebuild archive -project wkwebview.xcodeproj -scheme wkwebview -sdk iphoneos -configuration Debug clean build IPHONEOS_DEPLOYMENT_TARGET='15.0' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/wkwebview.app ~/Payload/
        zip -r wkwebview.ipa Payload

    - name: upload ipa
      uses: actions/upload-artifact@v2.2.0
      with:
        name: 'WKWebview'
        path: ~/wkwebview.ipa

    - uses: GuillaumeFalourd/copy-push-files@v1
      with:
        source_files: ~/wkwebview.ipa
        remote_repository: https://github.com/GitHub-auto-build-projects/swift-ios-wkwebview-demo
        access_token: ${{secrets.GITHUB_TOKEN}}
        target_dir: wkwebview
