name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: actual build
      run: set -o pipefail && xcodebuild archive -project wkwebview.xcodeproj -scheme wkwebview -sdk iphoneos -configuration Debug clean build IPHONEOS_DEPLOYMENT_TARGET='15.0' CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO | tee build.log | xcpretty

    - name: generate unsigned debug ipa
      run: |
        cd ~
        mkdir Payload
        mv ~/Library/Developer/Xcode/Archives/*/*/Products/Applications/wkwebview.app ~/Payload/
        zip -r wkwebview.ipa Payload

    - name: Upload APK to TestApp.io
      uses: testappio/github-action@v5
      with:
        api_token: ${{ secrets.TESTAPPIO_API_TOKEN }}
        app_id: ${{ secrets.TESTAPPIO_APP_ID }}
        file: ~/wkwebview.ipa
        git_release_notes: false
