name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Build and export iOS
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: wkwebview.xcodeproj
          scheme: wkwebview
          configuration: Release
          output-path: artifacts/wkwebview.ipa
          p12-base64: ${{ secrets.IOS_DISTRIBUTION_P12 }}
          certificate-password: ${{ secrets.IOS_CERTS_MDP }}
          mobileprovision-base64: ${{ secrets.IOS_PROFILE }}
          team-id: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload APK to TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{ secrets.TESTAPPIO_API_TOKEN }}
          app_id: ${{ secrets.TESTAPPIO_APP_ID }}
          file: artifacts/wkwebview.ipa
          release_notes: "Testing manual release notes..."
          git_release_notes: false
          include_git_commit_id: false
          notify: true
