name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - run: xcodebuild archive -project wkwebview.xcodeproj -scheme wkwebview -archivePath unsigned.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      
      - uses: "finnp/create-file-action@master
          env:
            FILE_NAME: "exportOptions.plist"
            FILE_DATA: "<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	 <key>compileBitcode</key>
	 <true/>
	 <key>method</key>
	 <string>ad-hoc</string>
	 <key>signingStyle</key>
	 <string>automatic</string>
	 <key>stripSwiftSymbols</key>
	 <true/>
	 <key>teamID</key>
	 <string>YourTeamID</string>
	 <key>thinning</key>
	 <string>&lt;none&gt;</string>
</dict>
</plist>"
